name: Deploy All Labs to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install and Build Lab3
        run: |
          cd lab3
          npm install
          npm run build

      - name: Prepare Public Folder
        run: |
          mkdir -p public_site
          # Копіюємо старі лаби (якщо вони існують у корені)
          cp -r lab1 public_site/ || echo "lab1 not found"
          cp -r lab2 public_site/ || echo "lab2 not found"
          # Копіюємо зібрану третю лабу в підпапку lab3
          cp -r lab3/dist public_site/lab3

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public_site
          branch: gh-pages